Feat/add output formatter options
microsoftgraph/msgraph-cli-core pull request #23
Opened 2022-03-03 21:33 UTC by calebkiage

2022-03-04 19:27 UTC, baywet commented on src/Microsoft.Graph.Cli.Core/IO/JsonOutputFormatter.cs
>  public class JsonOutputFormatter : IOutputFormatter
shouldn't bot those formatters live in the common lib so they could be reused by other CLIs?

2022-03-04 19:27 UTC, baywet requested changes
(see comment)

2022-03-10 16:27 UTC, calebkiage commented
https://github.com/microsoftgraph/msgraph-cli/issues/42
https://github.com/microsoftgraph/msgraph-cli/issues/49

2022-03-10 17:15 UTC, baywet approved these changes

2022-03-10 18:27 UTC, merged